/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantIndexRouteImport } from './routes/participant/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ParticipantTicketRouteImport } from './routes/participant/ticket'
import { Route as ManagerCreateRouteImport } from './routes/manager/create'
import { Route as ParticipantLotteryIdRouteImport } from './routes/participant/lottery/$id'
import { Route as ManagerLotteryIdRouteImport } from './routes/manager/lottery/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/participant/',
  path: '/participant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantTicketRoute = ParticipantTicketRouteImport.update({
  id: '/participant/ticket',
  path: '/participant/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCreateRoute = ManagerCreateRouteImport.update({
  id: '/manager/create',
  path: '/manager/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantLotteryIdRoute = ParticipantLotteryIdRouteImport.update({
  id: '/participant/lottery/$id',
  path: '/participant/lottery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLotteryIdRoute = ManagerLotteryIdRouteImport.update({
  id: '/manager/lottery/$id',
  path: '/manager/lottery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager/create': typeof ManagerCreateRoute
  '/participant/ticket': typeof ParticipantTicketRoute
  '/manager': typeof ManagerIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/manager/lottery/$id': typeof ManagerLotteryIdRoute
  '/participant/lottery/$id': typeof ParticipantLotteryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager/create': typeof ManagerCreateRoute
  '/participant/ticket': typeof ParticipantTicketRoute
  '/manager': typeof ManagerIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/manager/lottery/$id': typeof ManagerLotteryIdRoute
  '/participant/lottery/$id': typeof ParticipantLotteryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager/create': typeof ManagerCreateRoute
  '/participant/ticket': typeof ParticipantTicketRoute
  '/manager/': typeof ManagerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/manager/lottery/$id': typeof ManagerLotteryIdRoute
  '/participant/lottery/$id': typeof ParticipantLotteryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager/create'
    | '/participant/ticket'
    | '/manager'
    | '/participant'
    | '/manager/lottery/$id'
    | '/participant/lottery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager/create'
    | '/participant/ticket'
    | '/manager'
    | '/participant'
    | '/manager/lottery/$id'
    | '/participant/lottery/$id'
  id:
    | '__root__'
    | '/'
    | '/manager/create'
    | '/participant/ticket'
    | '/manager/'
    | '/participant/'
    | '/manager/lottery/$id'
    | '/participant/lottery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerCreateRoute: typeof ManagerCreateRoute
  ParticipantTicketRoute: typeof ParticipantTicketRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  ManagerLotteryIdRoute: typeof ManagerLotteryIdRoute
  ParticipantLotteryIdRoute: typeof ParticipantLotteryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/ticket': {
      id: '/participant/ticket'
      path: '/participant/ticket'
      fullPath: '/participant/ticket'
      preLoaderRoute: typeof ParticipantTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/create': {
      id: '/manager/create'
      path: '/manager/create'
      fullPath: '/manager/create'
      preLoaderRoute: typeof ManagerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/lottery/$id': {
      id: '/participant/lottery/$id'
      path: '/participant/lottery/$id'
      fullPath: '/participant/lottery/$id'
      preLoaderRoute: typeof ParticipantLotteryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/lottery/$id': {
      id: '/manager/lottery/$id'
      path: '/manager/lottery/$id'
      fullPath: '/manager/lottery/$id'
      preLoaderRoute: typeof ManagerLotteryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerCreateRoute: ManagerCreateRoute,
  ParticipantTicketRoute: ParticipantTicketRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
  ManagerLotteryIdRoute: ManagerLotteryIdRoute,
  ParticipantLotteryIdRoute: ParticipantLotteryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
